### ISSUE TITLE
Elastic Convert Locally

### ISSUE THREAD

**Issue by blakjord** [3CORESec/SIEGMA#10]
Hi, 
I'm trying to convert rules to elastic in locally without connecting to Kibana, and always reports me same error. 
`curl: (3) URL using bad/illegal format or missing URL. ` 
If I set the Kibana config it works, but always send a curl to check if the rule exists.
Can you enable a option to don't made a check to kibana server ? In testing mode don't upload automatically the rule, but it send the request to validate if exist the rule in kibana.

Thanks

**Comment by heyibrahimkhan** [comment]
Hi @blaijor 

Code has been updated.
From now on, enabling the "testing" switch will bypass the rule enablement status check.

**Comment by blakjord** [comment]
Okey, thanks
