### ISSUE TITLE
pyyaml module not detected in virtual env

### ISSUE THREAD

**Issue by akshayhari68** [3CORESec/SIEGMA#11]
![image](https://user-images.githubusercontent.com/42232364/187087222-d17fad04-738d-4b58-a45a-44aedbaafdee.png)

**Comment by heyibrahimkhan** [comment]
You can manually install the pyyaml module to fix the error
https://bobbyhadz.com/blog/python-no-module-named-yaml

We have the yaml module added to requirements.txt + the pipfile. Not exactly sure why it didn't get installed for your environment

Are you using the latest siegma commit from master branch?

Let us know if you are able to get the issue resolved.

**Comment by heyibrahimkhan** [comment]
Closed due to inactivity
