### ISSUE TITLE
sigma config

### ISSUE THREAD

**Issue by NahuFigueroa97** [3CORESec/SIEGMA#14]
Hi, great job! I have a question. Where is the sigma config that is required with the -sc parameter?

**Comment by heyibrahimkhan** [comment]
Hi @NahuFigueroa97 

That's basically the SIGMA schema you'd want to refer to for the relevant tool and datasource.

You can get that from SIGMA repo or create your own using samples like these.
https://github.com/SigmaHQ/legacy-sigmatools/blob/master/tools/config/ecs-cloudtrail.yml

**Comment by NahuFigueroa97** [comment]
Hi @heyibrahimkhan  With this tool I could enter a sigma rule and get the elastic equivalent?

**Comment by heyibrahimkhan** [comment]
Yes.. and more.

Basically, you get NOT just the query but the exact rule file and get that installed on the tool as well.
