### ISSUE TITLE
bad conversion sigma to elastic

### ISSUE THREAD

**Issue by NahuFigueroa97** [3CORESec/SIEGMA#15]
Hi, I have tried to convert this rule https://github.com/SigmaHQ/sigma/blob/9b39e2626099e11fa3679596d10b00a513974574/rules/windows/process_creation/proc_creation_win_powershell_base64_frombase64string.yml#L14 using this config https://github.com/SigmaHQ/legacy-sigmatools/blob/master/tools/config/powershell.yml. I get the following error:

```
06/09/24T00:25:06Z:ERROR:Exception Expecting value: line 1 column 1 (char 0) occurred in create_rule()... 06/09/24T00:25:06Z:INFO:Output file name: None... 06/09/24T00:25:06Z:ERROR:Ending script with error code: 1
```

**Comment by heyibrahimkhan** [comment]
The sigma config used seems to be an unrelated config for the mapping in the rule.

Try with this.
https://github.com/SigmaHQ/legacy-sigmatools/blob/master/tools/config/elk-winlogbeat-sp.yml
