### ISSUE TITLE
Add custom risk score capability

### ISSUE THREAD

**Issue by heyibrahimkhan** [3CORESec/SIEGMA#3]
Currently, risk score is set based on the risk level (low 25, medium 50, high 75 and critical 100) received from field "level" yml rule file.

Need to add a logic where risk_score in elastic output can be based on a custom field "score" in .yml file.

@DiogoBraz @0xtf , What do you think?

**Comment by 0xtf** [comment]
Is it worth keeping risk level in `level` and have a separate custom field? Or maybe they're used for different purposes?

**Comment by DiogoBraz** [comment]
What do we gain in creating an extra custom field for it? Isn't the level and risk score for the same purpose? If they serve the same purpose I do not see a problem in a direct mapping between "risk score" (SIEM) -> and -> "level" (Sigma). 
Although if they serve different purposes I would probably change my mind.

**Comment by 0xtf** [comment]
Problem I see is that the spec expects a value in form of:

level:
        type: //any
        of:
            - type: //str
              value: low
            - type: //str
              value: medium
            - type: //str
              value: high
            - type: //str
              value: critical

So this might be problematic for a direct mapping WHILE keeping true to the format of Sigma.

**Comment by DiogoBraz** [comment]
I expressed poorly. When I say direct mapping is simply what we are currently doing. Directly map the "level" sigma field to the "risk socre" field in SIEM. Yes i know we have hardcoded values , for example: if level sigma field is low, it will be directly mapped to SIEM field risk score with a value of 25. I'm not saying to map it with the original value of "low". My bad expressing... I only have doubts regarding the need of a custom field.

**Comment by heyibrahimkhan** [comment]
Right now, we have hard coded values.
If one has entered "level: low" in yml, he'll always get 25 in "risk_score" in elastic output.

What I'm trying to do is, let the user define what value he wants for score via custom field "score" in yml file, instead of our hard coded value.

**Comment by DiogoBraz** [comment]
I understand your ideia. The mapping would still be made from the field "level" from sigma rule, just during ingestion of the value you would give the ability for the user to set his own corresponding hardcoded values for the SIEM risk score to receive. Correct? 
If this is your idea I do not see any drawbacks from implementing it. Without user input would it take as default values the ones we currently use?

**Comment by heyibrahimkhan** [comment]
Not sure about during ingestion part.

I'm planning to give user the capability to define his custom risk score in yml rule file in a custom field "score", and not "level".
When siegma parses that rule, it will read the "score" field from yml and populate "risk_score" in elastic output accordignly.

**Comment by 0xtf** [comment]
I think that it's good to provide additional control over the outcome. At the end, more control over the consumables is why the project exists. 

Ideally we don't deviate from Sigma unless we need to. Based on that, my recommendation is:

* `level` would be kept as standard and would perform mapping as it does right now
* If user wants to have more control there could be a `risk_score` field
  * If `risk_score` is present it takes precedence over the `level` field

Don't know how feasible it is but I think this is a good balance between keeping close to standard Sigma while providing the advanced options we aim to have in SIEGMA.

**Comment by heyibrahimkhan** [comment]
Agreed.

**Comment by heyibrahimkhan** [comment]
Feature implemented.
