### ISSUE TITLE
Fields passed as arguments

### ISSUE THREAD

**Issue by 0xtf** [3CORESec/SIEGMA#4]
**General idea:** While there are many fields in a particular config that are set per environment a few can be dependent on a particular rule. For example, we might wish to associate a ``timeline_id`` from Elastic SIEM to a particular rule or rule folder. 

With the possibility of passing arguments for a specific configuration we can provide additional functionality that aids in automation while refraining from hard coding fields in the config.

Example:

`siegma.py ARGUMENTS -f timeline_id=111,timeline_description=222`

Just an idea. Feedback welcome.

**Comment by heyibrahimkhan** [comment]
Feature added.
