### ISSUE TITLE
Problem with multiple detections in one file

### ISSUE THREAD

**Issue by felix-lessoer** [3CORESec/SIEGMA#7]
It looks like there is an issue when detecting multiple documents in one file.
This is the file that leads into the following issue for me:
https://github.com/SigmaHQ/sigma/blob/master/rules/linux/auditd/lnx_auditd_cve_2021_3156_sudo_buffer_overflow.yml

```04/01/21T11:45:43Z:ERROR:Exception expected a single document in the stream
  in "sigma/rules/linux\auditd\lnx_auditd_cve_2021_3156_sudo_buffer_overflow.yml", line 1, column 1
but found another document
  in "sigma/rules/linux\auditd\lnx_auditd_cve_2021_3156_sudo_buffer_overflow.yml", line 23, column 1 occurred in main of file siegma.py...
04/01/21T11:45:43Z:ERROR:Ending script with error code: 1```

**Comment by 0xtf** [comment]
Hi @felix-lessoer, thanks for bringing this to our attention. We'll look into it and get back to you ASAP.

**Comment by heyibrahimkhan** [comment]
Hi @felix-lessoer , Thanks for raising it.

The way we built SIEGMA was so it can take individual rules and install them on the relevant platform while making use of rule "ID" as the uniquely identifying value for each of the rules.

For one rule to have multiple detection document, though works for sigma, but it breaks the logical flow of SIEGMA & how it is supposed to uniquely interpret rules. 
Besides this, multiple documents within the same rule file open room for limitless possibilities for objects other than "detection" which would be far too broad to ever cover.

Also, as of now, "es-qs" is the only backend supported with siegma. And that backend does not support aggregation queries.
ETA for that feature is unknown.

Therefore, as a partial fix for your issue, we'd suggest to do following and only then try again with SIEGMA:
- Split the current rule file into 2 separate rule files containing 1 detection document each.
- And remove the query portion from pipe symbol and after. See attached screenshot for example. 
![image](https://user-images.githubusercontent.com/14034237/113320830-66f35800-932c-11eb-86c4-e3874c276209.png)


Still, SIEGMA execution on those 2 newly created rule files would fail until:
- Aggregation based queries for "es-qs" are implemented at sigma level.
- OR, support for a query language that can handle aggregation is implemented in SIEGMA. We can put it on our roadmap to add that language support for your relevant aggregation based query language in SIEGMA.

Feel free to let us know if this helps.

**Comment by felix-lessoer** [comment]
Thanks a lot.
For now I will just skip detections that have this issue.
I just want to create a complete set of the sigma rules for the ES detection engine to share this here: 
https://elastic-content-share.eu/

Btw: is this okay for you if I mention your repo as source?

**Comment by heyibrahimkhan** [comment]
Sure @felix-lessoer.

Feel free to reference any relevant 3CORESec projects there.

**Comment by 0xtf** [comment]
Guess we can close this one for now. Thanks for the feedback @felix-lessoer. Feel free to reach out if we can help further.
