### ISSUE TITLE
Logo - Greek alphabet off-by-some

### ISSUE THREAD

**Issue by gcrow** [3CORESec/SIEGMA#8]
The 'E' in the Greek alphabet is epsilon.

The 'S' is Sigma.

Everytime I look at the logo with a Σ for a lower case 'e' I die a little inside, and I'm not even Greek.

Any chance of fixing it?

**Comment by 0xtf** [comment]
Fair point! We'll look into it. Thank you for bringing it to our attention.

**Comment by 0xtf** [comment]
Updated the workflow image with https://github.com/3CORESec/SIEGMA/commit/6b7ed1e2c7a74ea0060cea1d6a186c5f79f4a8c4. 

My OCD is killing me we can't do anything on the Twitter posts in which we butchered the Greek alphabet. 😕 Going forward though, we'll make sure to use the updated logo.

Again, thank you for bringing this to our attention @gcrow! If you find anything else please let us know.
